import os
import re
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from langchain_core.documents import Document
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_text_splitters import RecursiveCharacterTextSplitter
from rank_bm25 import BM25Okapi
import pdfplumber
import streamlit as st

from utils.ocr_cleaner import clean_ocr


@dataclass
class Pipeline:
    db: Any
    bm25: Any
    texts: list
    chunks: list
    embeddings: Any
    llm: Any


def clean_chunk_text(text: str) -> str:
    """Fix common PDF extraction issues: missing spaces, garbled runs, broken hyphens."""
    text = re.sub(r'([a-z])([A-Z])', r'\1 \2', text)   # camelCase → camel Case
    text = re.sub(r'(\w)-\s+(\w)', r'\1\2', text)       # broken hy- phens
    text = re.sub(r'\s+', ' ', text)                    # collapse whitespace
    return text.strip()

def extract_pdf(pdf_path):
    documents = []
    try:
        with pdfplumber.open(pdf_path) as pdf:
            for page_num, page in enumerate(pdf.pages):
                text = page.extract_text() or ""
                table_text = ""
                tables = page.extract_tables()
                for table in tables:
                    for row in table:
                        clean_row = [str(cell).strip() for cell in row if cell and str(cell).strip()]
                        if clean_row:
                            table_text += " | ".join(clean_row) + "\n"
                full_text = clean_ocr(text + "\n" + table_text)
                if len(full_text.strip()) > 50:
                    documents.append(Document(
                        page_content=full_text,
                        metadata={"source": "brochure.pdf", "page": page_num + 1}
                    ))
        print(f"[PDF] Extracted {len(documents)} pages")
    except Exception as e:
        print(f"[PDF] Error: {e}")
    return documents

def load_scraped_data(raw_dir="data/raw"):
    documents = []
    raw_path = Path(raw_dir)

    if not raw_path.exists():
        print("[SCRAPER] data/raw/ not found — run: python src/mastersunion_scraper.py")
        return documents

    combined_files = list(raw_path.glob("*_full.txt"))
    if not combined_files:
        combined_files = list(raw_path.glob("**/*.txt"))

    for file in combined_files:
        try:
            text = file.read_text(encoding="utf-8")
            if len(text.strip()) < 100:
                continue
            first_line = text.split("\n")[0]
            course_name = first_line.replace("COURSE:", "").strip() if "COURSE:" in first_line else file.stem
            documents.append(Document(
                page_content=text,
                metadata={"source": str(file), "course": course_name, "page": file.stem}
            ))
            print(f"[SCRAPER] Loaded {file.name} ({len(text):,} chars)")
        except Exception as e:
            print(f"[SCRAPER] Error loading {file}: {e}")

    print(f"[SCRAPER] Total: {len(documents)} documents loaded")
    return documents

@st.cache_resource
def load_pipeline():
    # Step 1: Load PDF brochure
    pdf_docs = extract_pdf("data/brochure.pdf")

    # Step 2: Load TXT documentation
    txt_docs = []
    try:
        with open("data/program_data.txt", "r", encoding="utf-8") as f:
            txt_content = f.read()
        txt_docs.append(Document(
            page_content=txt_content,
            metadata={"source": "program_data.txt", "page": "documentation"}
        ))
        print(f"[TXT] Loaded program_data.txt ({len(txt_content)} chars)")
    except Exception as e:
        print(f"[TXT] Error: {e}")

    # Step 3: Scraped data (pre-generated by src/mastersunion_scraper.py)
    scraped_docs = load_scraped_data("data/raw")

    all_docs = pdf_docs + txt_docs + scraped_docs
    print(f"[PIPELINE] PDF:{len(pdf_docs)} TXT:{len(txt_docs)} Scraped:{len(scraped_docs)} Total:{len(all_docs)}")

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=200,
        separators=["\n\n", "\n", ".", "!", "?", ",", " "]
    )
    chunks = splitter.split_documents(all_docs)
    for c in chunks:
        c.page_content = clean_chunk_text(c.page_content)
    texts = [c.page_content for c in chunks]
    print(f"[PIPELINE] Total chunks: {len(chunks)}")

    embeddings = HuggingFaceEmbeddings(
        model_name="sentence-transformers/all-MiniLM-L6-v2"
    )
    FAISS_INDEX_PATH = "./faiss_index"

    # Rebuild index if program_data.txt is newer than the saved index
    if os.path.exists(FAISS_INDEX_PATH):
        index_mtime = os.path.getmtime(FAISS_INDEX_PATH)
        data_mtime = os.path.getmtime("data/program_data.txt") if os.path.exists("data/program_data.txt") else 0
        if data_mtime > index_mtime:
            shutil.rmtree(FAISS_INDEX_PATH)
            print("[FAISS] Source data newer than index — rebuilding")

    FAISS_SENTINEL = os.path.join(FAISS_INDEX_PATH, ".built_by_app")

    if os.path.exists(FAISS_INDEX_PATH):
        if not os.path.exists(FAISS_SENTINEL):
            # Index directory exists but was not created by this app — rebuild to be safe
            shutil.rmtree(FAISS_INDEX_PATH)
            print("[FAISS] Sentinel missing — untrusted index removed, rebuilding")

    if os.path.exists(FAISS_INDEX_PATH):
        # allow_dangerous_deserialization is required by FAISS (uses pickle).
        # The sentinel file above ensures this index was written by this application
        # and has not been replaced by an external actor.
        db = FAISS.load_local(
            FAISS_INDEX_PATH,
            embeddings,
            allow_dangerous_deserialization=True
        )
        print("[FAISS] Loaded existing index")
    else:
        db = FAISS.from_documents(chunks, embeddings)
        db.save_local(FAISS_INDEX_PATH)
        # Write sentinel to mark this index as trusted
        Path(FAISS_SENTINEL).touch()
        print("[FAISS] Built and saved new index")

    tokenized = [t.lower().split() for t in texts]
    bm25 = BM25Okapi(tokenized)

    print("[PIPELINE] Using fast keyword intent classifier")

    # ── LLM toggle: read from st.secrets first, fall back to env ─────────────
    USE_LOCAL_LLM = (
        st.secrets.get("USE_LOCAL_LLM", os.environ.get("USE_LOCAL_LLM", "false"))
    ).lower() == "true"

    if USE_LOCAL_LLM:
        from langchain_ollama import ChatOllama
        llm = ChatOllama(
            model="qwen3:1.7b",
            temperature=0,
            base_url=os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434"),
            num_ctx=4096,
            num_predict=2048,
            num_thread=8,
            num_batch=512,
            repeat_penalty=1.1,
            stream=True,
            think=False,  # Disable chain-of-thought — avoids empty answers when token budget runs out
        )
    else:
        from langchain_openai import ChatOpenAI
        llm = ChatOpenAI(
            model="gpt-4o-mini",
            temperature=0,
            api_key=st.secrets.get("OPENAI_API_KEY", os.environ.get("OPENAI_API_KEY", "")),
        )

    return Pipeline(db=db, bm25=bm25, texts=texts, chunks=chunks, embeddings=embeddings, llm=llm)